Improve test stability
 DayTableTest > beginAndEndDeletedWhenChangingDayTypeToSick() FAILED
    org.opentest4j.MultipleFailuresError at DayTableTest.java:112
        Caused by: org.opentest4j.AssertionFailedError at DayTableTest.java:112

DayTableTest.beginAndEndDeletedWhenChangingDayTypeToSick()

org.opentest4j.MultipleFailuresError: Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: [begin]
expected: null
but was : 11:16