Don't crash during startup when there is a problem with plugins
java.lang.NullPointerException: Code source security was null
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getPermissions(JNLPClassLoader.java:1085) ~[?:?]
	at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:119) ~[?:?]
	at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:252) ~[?:?]
	at java.security.ProtectionDomain.implies(ProtectionDomain.java:321) ~[?:?]
	at java.security.ProtectionDomain.impliesWithAltFilePerm(ProtectionDomain.java:353) ~[?:?]
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:450) ~[?:?]
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getAccessControlContextForClassLoading(JNLPClassLoader.java:2083) ~[?:?]
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.findClass(JNLPClassLoader.java:1590) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:575) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.itsallcode.whiterabbit.plugin.pmsmart.PMSmartExportPlugin.supports(PMSmartExportPlugin.java:21) ~[?:?]
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginWrapper.supports(PluginWrapper.java:40) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginManager.lambda$findPluginsSupporting$0(PluginManager.java:41) ~[whiterabbitfx-signed.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginManager.findPluginsSupporting(PluginManager.java:43) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginManager.getUniqueFeature(PluginManager.java:58) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginManager.getMonthDataStorage(PluginManager.java:53) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.logic.service.AppService.createMonthDataStorage(AppService.java:120) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.logic.service.AppService.create(AppService.java:100) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.jfxui.JavaFxApp.doInitialize(JavaFxApp.java:100) ~[whiterabbitfx-signed.jar:?]
	at org.itsallcode.whiterabbit.jfxui.JavaFxApp.init(JavaFxApp.java:82) ~[whiterabbitfx-signed.jar:?]
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824) ~[whiterabbitfx-signed.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195) ~[whiterabbitfx-signed.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]